name: CI/CD

on: [push]

jobs:
  pipeline:
    name: Pipeline
    uses: GitHub-Accelerate/GH-Workflows/.github/workflows/java_pipeline.yml@main
    with:
      java-version: '17'
    secrets: inherit

  file-existence-check:
    runs-on: ubuntu-latest
    steps:
      - name: Verify file present
        run: |
          echo "Will test for important files that may be missing"

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: "manifest.yml"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        # Only runs if all of the files exists
        run: echo All files exists!
