name: CI/CD

on: [push]

jobs:
  pipeline:
    name: Pipeline
    uses: GitHub-Accelerate/GH-Workflows/.github/workflows/java_pipeline.yml@main
    with:
      java_version: '16'
    secrets: inherit

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo Hi :-)
