name: Snapshot

on:
  workflow_dispatch:
    inputs:
      createRelease:
        description: 'Create a release'
        required: true
        type: boolean
      deployEnv:
        description: 'Deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - qa
        - prod
      deployVersion:
        description: 'Deployment version'
        type: string
        required: true

jobs:
  snapshot:
    name: Snapshot
    uses: GitHub-Accelerate/GH-Intermediate-Workflows/.github/workflows/snapshot.yml@main
    with:
      createRelease: ${{ inputs.createRelease }}
      deployEnv: ${{ inputs.deployEnv }}
      deployVersion: ${{ inputs.deployVersion }}
    secrets: inherit
